### ISSUE TITLE
Problems parsing CNTB, CNTE & PRIM chunks

### ISSUE THREAD

**Issue by RaymondTFreeman** [cdyk/rvmparser#17]
I have trying to parse an RVM file and have had a bit of trouble doing so, both PUC and rvmparser run into problems with it. The first two problems were that OBST and INSU chunks are not recognized. I managed to work around the unrecognized chunks by incrementing the file pointer to the start of the next chunk:

```
    // process children
    char chunk_id[5] = { 0, 0, 0, 0, 0 };
    auto l = p;
    uint32_t len, dunno;
    p = parse_chunk_header(chunk_id, len, dunno, p, e);
    auto id_chunk_id = id(chunk_id);
    while (p < e && id_chunk_id != id("CNTE")) {
      switch (id_chunk_id) {
      case id("CNTB"):
        p = parse_cntb(ctx, p, e);
        if (p == nullptr) return p;
        break;
      case id("PRIM"):
        p = parse_prim(ctx, p, e);
        if (p == nullptr) return p;
        break;
      case id("OBST"):
        //fprintf(stderr, "Warning: Skipping OBST chunk of %u (=0x%x) bytes.\n", len, len);
        p = reinterpret_cast<const char*>(start_of_file_ptr) + len;
        break;
      case id("INSU"):
        //fprintf(stderr, "Warning: Skipping INSU chunk of %u (=0x%x) bytes.\n", len, len);
        p = reinterpret_cast<const char*>(start_of_file_ptr) + len;
        break;
      default:
        snprintf(ctx->buf, ctx->buf_size, "In CNTB, unknown chunk id %s", chunk_id);
        ctx->store->setErrorString(ctx->buf);
        return nullptr;
      }
      l = p;
      p = parse_chunk_header(chunk_id, len, dunno, p, e);
      id_chunk_id = id(chunk_id);
    }
```

Then I began getting assertion fails when reading the headers and after looking through the file in a hex editor I added this little hack just to get it working:
```
    if (p[0] != 0 || p[1] != 0 || p[2] != 0) {
      p += 4;
    }
    for (i = 0; i < 4 && p + 4 <= e; i++) {
      assert(p[0] == 0);
      assert(p[1] == 0);
      assert(p[2] == 0);
      id[i] = p[3];
      p += 4;
    }
    for (; i < 4; i++) {
      id[i] = ' ';
    }
```
The first 3 lines are my addition, not exactly satisfied but it worked.

I'm still digging through the data and I'll update this issue as I figure things out, I'll probably open up a pull request later, until then any input would be much appreciated.

**Comment by RaymondTFreeman** [comment]
Figured it out. Every offset error is preceded by a version 3 CNTB. There is an extra 32 bit field at the end.

Adding the following lines after reading the translation and group material ID in the `parse_cnbt` function solved the problem for me:
```
    if (version > 2) {
      uint32_t dunno;
      p = read_uint32_be(dunno, p, e);
    }
```

**Comment by cdyk** [comment]
Thanks @RaymondTFreeman! I added your fix.

Can you please verify that this PR works with a file that contains such a chunk?

FYI: Interpreting OBST and INSU chunks is discussed in issue https://github.com/cdyk/rvmparser/issues/16

**Comment by cdyk** [comment]
Fixed in https://github.com/cdyk/rvmparser/pull/33
