### ISSUE TITLE
Option to base-64 embed data buffer in GLTF instead of using GLB container

### ISSUE THREAD

**Issue by cdyk** [cdyk/rvmparser#25]
This wil produce a GLTF file that is pure ascii text instead of embedding it into a GLB container.

This will increase file size by around 33%, but should work on applications that do not support GLB containers

**Comment by vegarringdal** [comment]
Being able to split with a option on what level like discussed in #48 will solve this issue ?

**Comment by cdyk** [comment]
GLTF files are bigger than GLB files since the buffer data is encoded as base64 instead of stored in raw form, so if just the file size is the issue, this won't help. But when writing as GLTF, the buffers are not packed into one single buffer but as a lot of small buffers, so that might help in some cases where a single large buffer is an issue.

**Comment by cdyk** [comment]
Implemented in #52.
