### ISSUE TITLE
Something wrong with gltf normals

### ISSUE THREAD

**Issue by mixtur** [cdyk/rvmparser#26]
It seems there is something wrong with normals you generate for gltf files.

From what it looks like in Blender, the normals (pink lines) are all pointing out of some "center" which is wrong in general. In this case they should probably be aligned with face normals.

![image](https://user-images.githubusercontent.com/2968077/124487551-8a102680-ddb7-11eb-9ffe-428dc6e4ff56.png)

RVM file taken from here: https://github.com/benvautrin/pmuc/tree/master/data

Thank you.

**Comment by cdyk** [comment]
Indeed, more or less all normals look off. Have you tried going via an obj file instead of gltf?

**Comment by mixtur** [comment]
Thank you for the quick response.

Tried to convert to .obj too. Blender was unable to open the result.

It reported the following:

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_obj\__init__.py", line 146, in execute
    return import_obj.load(context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_obj\import_obj.py", line 1065, in load
    vdata, vec, vdata_len)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_obj\import_obj.py", line 938, in handle_vec
    vec[:] = [float_func(v) for v in line_split[1:]]
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\addons\io_scene_obj\import_obj.py", line 938, in <listcomp>
    vec[:] = [float_func(v) for v in line_split[1:]]
ValueError: could not convert string to float: b'-nan(ind)'

location: <unknown location>:-1
```

I also opened offended .obj in Notepad++ and there it was:
![image](https://user-images.githubusercontent.com/2968077/124492171-c5f9ba80-ddbc-11eb-9236-de2669be4ad5.png)

**Comment by cdyk** [comment]
Nan-issue (was zero-length normals due to degenerate geometry) is fixed in PR https://github.com/cdyk/rvmparser/pull/27 , so obj-output looks decent.

Some shapes in that file have inverted normals, but those are of type FacetGroup that has vertex positions and normals directly provided by the RVM file.

Though, gltf-output is still broken.

**Comment by cdyk** [comment]
Found it, vertex position was used as normal, fixed in PR https://github.com/cdyk/rvmparser/pull/28. Gltf-output looks nice.

**Comment by mixtur** [comment]
Awesome! Thank you.
