### ISSUE TITLE
Is there specification on RVM file format?

### ISSUE THREAD

**Issue by mixtur** [cdyk/rvmparser#29]
I wasn't able to find any document describing rvm file format.

[pmuc](https://github.com/benvautrin/pmuc) - says in their CREDITS section about some document

> This work has been led and founded by EDF DIN. It has been based on an analysis made by Kristian Sons from Supporting GmbH.

But I couldn't find that either. 

Where can I find any information about the format? Where do you find it?

**Comment by cdyk** [comment]
There is no publicly available specification as far as I know.

My information comes mainly from looking at a ton of rvm files in a hex editor, trying to parse them and looking at the resulting geometry.

Luckily the format is very structured and have a straightforward encoding.

Though, there are parts of the files that are currently unknown and ignored, and coverage of geometry types and chunks is limited to the set that I have encountered.

**Comment by mixtur** [comment]
Thank you
