### ISSUE TITLE
Found another model that produces nan(ind) in normals when converting to OBJ

### ISSUE THREAD

**Issue by mixtur** [cdyk/rvmparser#30]
Here is the model: [Area_02_SEARCH.zip](https://github.com/cdyk/rvmparser/files/6770853/Area_02_SEARCH.zip)

**Comment by cdyk** [comment]
Snout with zero height produces the degenerate normals. Extended NaN-handling to cover the situation that there is a NaN in the nornal in the first place. See PR https://github.com/cdyk/rvmparser/pull/32 .
