### ISSUE TITLE
Invalid glb

### ISSUE THREAD

**Issue by mixtur** [cdyk/rvmparser#31]
When converting these files [area02_ch2_hvac.zip](https://github.com/cdyk/rvmparser/files/6770960/area02_ch2_hvac.zip) to glb, the resulting glb is invalid.

It seems JSON section of the file suddenly ends and a binary part starts from there. Some buffer is too small maybe?

**Comment by cdyk** [comment]
glb is json with geometry data stored as binary, and it looks correct here.

**Comment by mixtur** [comment]
By "suddenly" I mean that the JSON part is incomplete. It ends with something like `[1,2,3` And binary starts just after that.

**Comment by mixtur** [comment]
Here is what I see:
![image](https://user-images.githubusercontent.com/2968077/124733004-729e7e00-df1c-11eb-8cc8-543c09432020.png)

Maybe there is something wrong with my build or execution environment. I tried both on Windows and Linux. The result is the same.

On Windows I have Visual Studio Community 2019 (Version 16.10.3)
On Linux - clang version 10.0.0-4ubuntu1, locale is LANG=ru_RU.UTF-8

**Comment by mixtur** [comment]
Ow. After pulling the `nan` handling - everything is fine. That is weird.

**Comment by mixtur** [comment]
Could it be because I tried to output both GLB and OBJ simultaneously with `--tolerance=0.01 --output-gltf=file.glb --output-obj=file area02_ch2_hvac.RVM area02_ch2_hvac.ATT`?

**Comment by cdyk** [comment]
Seems like nan/infinity is illegal in json, and rapidjson (which does json encoding here) stops writing when encountering that.

**Comment by mixtur** [comment]
Oh. I see.

I think I can close this now. But may I suggest some improvements anyway:

- if the tool could report that it failed to generate JSON - it would be very nice.
- if it could also explain why - it would be perfect
- there's no need to output min/max for attributes other than POSITION, and that is what probably happen

Thank you.
