### ISSUE TITLE
question: demo rvm files

### ISSUE THREAD

**Issue by VegarRingdalAibel** [cdyk/rvmparser#35]
Since you have been working with RVM files Im wondering if you have any demo RVM files of different sizes you can share?
All files I have is company files, so I can't really show anyone videos from a web viewer I've been working on that use your rvm parser result

**Comment by cdyk** [comment]
Unfortunately not, the only public model I know of is pmuc's sample data file:

https://github.com/benvautrin/pmuc/tree/master/data

**Comment by VegarRingdalAibel** [comment]
ok, thank you.
Was hoping to find model on 500-1000mb size

**Comment by Strepto** [comment]
Hey, I just noticed this. Equinor has published the Huldra RVM dataset, including ~500mb of RVM data for the Huldra platform with a permissive license. So not a very big model, but if you duplicate it 20 times its close to a modern asset :D 

It can be found on: https://data.equinor.com

Login can be tricky, but I usually use a "in-private window", and allow popups. Use the B2C login button, and create a user to get access.

**Comment by cdyk** [comment]
Thanks, that is very interesting!

**Comment by vegarringdal** [comment]
Nice. 

Finally a rvm file I can share some of my weird stuff Ive been doing at work/private :-)

@Strepto thx

**Comment by vegarringdal** [comment]
Finally got around to try the RVM files

![image](https://user-images.githubusercontent.com/2901416/196046502-ece8292f-ab87-4f02-9873-acc8f1b0379a.png)

**Comment by cdyk** [comment]
Nice!

**Comment by vegarringdal** [comment]
Even made a small video: https://www.youtube.com/watch?v=FzTHbogfr5k

**Comment by Strepto** [comment]
_Very_ impressive video!

**Comment by vegarringdal** [comment]
@Strepto 

Thx, Im lucky @cdyk made this RVM parser, tried to use E3D ifc export, but was easier to use RVM part so we could reused already exported files.

I just need to learn more c++ so I can optimise it a little for my weird needs for my custom format I need in backend.
