### ISSUE TITLE
question

### ISSUE THREAD

**Issue by VegarRingdalAibel** [cdyk/rvmparser#36]
@cdyk 

Trying to learn c++
I have so much to learn :-)

if you have time/want to, could you help me understand this part?
`rv = q[0] << 24 | q[1] << 16 | q[2] << 8 | q[3];`

![image](https://user-images.githubusercontent.com/94840334/197264508-57c39929-6c9d-43aa-95d3-31c31a886292.png)

If you dont have time/or do not want to, then thats ok :-)

**Comment by cdyk** [comment]
No problem. 

When accessing data bigger than a byte (this case 32 bit/4 bytes) from something byte oriented (memory and files), there is a question in what order to store these 4 bytes.

Two common, and opposite, choices are 'big endian' and 'little endian'

This function reads a 32bit integer stored as big endian (hence the _be suffix); the byte on the lowest address q[0] gets shifted 24 bits up so it becomes the highest 8 bits in the resulting 32 bits.

**Comment by VegarRingdalAibel** [comment]
Thank you.
