### ISSUE TITLE
Question/Feature request

### ISSUE THREAD

**Issue by vegarringdal** [cdyk/rvmparser#48]
Hi

Noticed you been really active lately 👍 

Is it possible to get it to produce 1 glb per top level/site in the RVM ?
This would reduce glb size, and memory usages while converting and using the glb files.

I have a modified version here:
* https://github.com/VegarRingdalAibel/rvmparser/commits/file_per_site
But its producing json/bin as separate files, since we didnt know how to read glb files to begin with 😂 
And I know very little about c++, so Im sure I have done many weird and bad things.
Having a split per top level/site in your repo would be a valuable option for all users.
I also convert the entire file first then glbs. Converting per site & producing glb file would lower the memory usage a lot more, but I had no clue to how to do it. And havent had time to look into it yet... 

c++ is still on my todo list 😂 

Other issue:
https://github.com/VegarRingdalAibel/rvmparser/commit/6f2d8ede1880ab5275d746016cc68d355a72ba1b

I did some weird workaround here because of items without geometry, dunno if you have added a fix for this ?
I only checked first element..

**Comment by cdyk** [comment]
Creating glbs for different subtrees should be pretty straightforward. The hardest path is figuring a good way to specify this, how the hierarchy is structured appear to vary between companies, just splitting at a certain tree level is the simple approach?

Wrt the segfault, please make a separate issue for that along with either a callstack of the segfault or the file/linenumber to the code in tessellation that triggers the segfault. The right approach there is to just skip tessellating degenerate geometry with a warning.

**Comment by vegarringdal** [comment]
Splitting at a certain tree level sounds like a very good idea, and very flexible 🥇

**Comment by Krande** [comment]
+1 from me. Having the option to split at specified tree level and output 1 glb per level would really help with memory usage on some of our really big models :)

**Comment by cdyk** [comment]
Implemented in #53 (and included in v1.0.1).

**Comment by vegarringdal** [comment]
Amazing 🎉👍
Will check it out tomorrow.

**Comment by VegarRingdalAibel** [comment]
Gave it a quick try earlier today, looks very promising, ended up with 202 glb files.  😄 

Will give more try during the week.
Thank you for taking the time to add this feature 👍
