### ISSUE TITLE
bug: segfault if item have no geometry

### ISSUE THREAD

**Issue by vegarringdal** [cdyk/rvmparser#50]
I did some weird workaround here because of items without geometry, dunno if you have added a fix for this ?
I only checked first element..

https://github.com/VegarRingdalAibel/rvmparser/commit/6f2d8ede1880ab5275d746016cc68d355a72ba1b

![image](https://user-images.githubusercontent.com/2901416/207878334-1e5cf904-f14f-4563-a623-68e8a78180c9.png)

I will try and supply a file where I can reproduce this issue, just hope I find it again. :-)

**Comment by cdyk** [comment]
This is probably enough. It looks like a model with garbage in a contour in a facet set geometry, and that primitive should be ignored in the tessellator IMO

**Comment by vegarringdal** [comment]
You know this a lot better then me. :-) Not been able to find the bad model again, so models might have been cleaned up.
I just want your source to be the source of our convert jobs if possible, since you have updated external libs etc.
Really like you have added some github actions to make builds. 👍 
I can make a PR if you want, but maybe its easier for you to just add directly ?

**Comment by cdyk** [comment]
Fixed. Please reopen issue if problem persists.

**Comment by vegarringdal** [comment]
will do, thx 🥇 
plan is to try and move our pipeline into using your build if you get get time to implement #48.
