### ISSUE TITLE
After chunk PRIM, expected offset 0x8f84, current offset is 0x100008f84

### ISSUE THREAD

**Issue by VegarRingdalAibel** [cdyk/rvmparser#54]
Think I found a bug if trying to parse a really big rvm file, this one is almost 4.3 gig

![image](https://user-images.githubusercontent.com/94840334/208890950-1903bb8b-ae23-4554-a1cd-5e2e9e9ce34e.png)

Wonder if this fixed it earlier of my branch
Dont have visual studio installed atm, so hard to test

![image](https://user-images.githubusercontent.com/94840334/208891033-c41edac5-055b-447b-bdd6-e9ceabdaa0a5.png)

**Comment by cdyk** [comment]
Yes, I thought I already had fixed that. Fixed in #55.

**Comment by VegarRingdalAibel** [comment]
nice, Ill give it a test right away

**Comment by VegarRingdalAibel** [comment]
It managed to read and started producing glb files, so looks good 🥇 👍
