### ISSUE TITLE
question/feature request - validate changes

### ISSUE THREAD

**Issue by VegarRingdalAibel** [cdyk/rvmparser#58]
I do not know if this is possible or easy.

When using  `--output-gltf-split-level` it would be nice to know if RVM input for that level is same as last convert time I converted.
Is it possible to add like a mdf/sha1 id in the meta data based exported lvl ?

I guess if I try and do something like that on the gltf I might not get correct result due precision etc ?

**Comment by cdyk** [comment]
If center model is true, changing any geometry might change the center slightly, so that might change everything. But if that is off, I think parts should be relatively independent.

Have you tried to just create hashes of the output file and see if all of them change?

**Comment by VegarRingdalAibel** [comment]
Looks like it recreated very similar on the same file, think we just need to test it out

![image](https://user-images.githubusercontent.com/2901416/214901222-84216323-8e87-49a5-9f2c-e8dc5d4591ea.png)
