### ISSUE TITLE
Failed to parse : Unrecognized chunk CNTE

### ISSUE THREAD

**Issue by liuyichuan** [cdyk/rvmparser#60]
Hi! 
I export a rvm binary file from AM. Got this error when parse it to gltf.
[emptyasm.zip](https://github.com/cdyk/rvmparser/files/10906236/emptyasm.zip)
 
And I export it to text rvm. Found an extra CNTE with no CNTB is following. 

This error should be handled or not? 

Thanks.

**Comment by cdyk** [comment]
Thanks for the file!

Yes, indeed, there is an extra CNTE chunk at the end of the file before the END: chunk.

I added the case with a warning so the file will parse just emitting a warning instead of failing.
