### ISSUE TITLE
What's the format of --keep-groups file?

### ISSUE THREAD

**Issue by ld000** [cdyk/rvmparser#65]
When I add --keep-groups parameter and run, then got the error "segmentation fault  ./rvmparser --output-obj=aaa --keep-groups=group.txt".
What's the format of --keep-groups file?

**Comment by cdyk** [comment]
It should be a text file with a group name on each line. It is read here: https://github.com/cdyk/rvmparser/blob/cfc6114ebdb55e92ba992b9638a7683541348d5f/src/Flatten.cpp#L13

**Comment by ld000** [comment]
thx!
