### ISSUE TITLE
hi i am getting error while parsing RVM

### ISSUE THREAD

**Issue by dhananjaykrpandey** [cdyk/rvmparser#8]
hi i am getting error while parsing RVM

Failed to parse C:\c++\rvmparser\msvc15\x64\Debug\URP_PIP_572_BR5.rvm: Unrecognized chunk COLR
[I] Stats:
[I]     Groups                 3381
[I]     Geometries             8669 (grp avg=2.6)
[I]         Pyramids           0
[I]         Boxes              5678
[I]         Rectangular tori   0
[I]         Circular tori      157
[I]         Elliptical dish    2
[I]         Spherical dish     0
[I]         Snouts             0
[I]         Cylinders          1621
[I]         Spheres            0
[I]         Facet groups       1211
[I]             triangles      62
[I]             quads          44444
[I]             polygons       21739 (fgrp avg=18.0)
[I]                 contours   23441 (poly avg=1.1)
[I]                 vertices   184886 (cont avg=7.9)
[I]         Lines              0

C:\c++\rvmparser\msvc15\x64\Debug\rvmparser.exe (process 9812) exited with code -1.

**Comment by cdyk** [comment]
Hi, I have never encountered that kind of chunk in any of my test files, so rvmparser doesn't handle it.

You might try to ignore it by adding a case for it in

https://github.com/cdyk/rvmparser/blob/037551b508d5ee92cacb84247655d2e5ff1faf18/src/ParserRVM.cpp#L377

and incrementing `p` by `len`

**Comment by dhananjaykrpandey** [comment]
Thanks Christopher;
https://letsupload.co/3s0iu/2017-11-27-URP.7z
https://letsupload.co/3s0iw/2017-11-27-USP.7z
I uploade my rvm files in this location , can you please help me 
i am not that much expert in c++ , i am C# developer

**Comment by cdyk** [comment]
Hi, I added code to skip COLR chunks. Please try the branch skip_colr and see if that works.

**Comment by dnsn021** [comment]
Hi, the color chunk will be generated by pml commands, I tried to parse this by following codes:
<details>
<summary>parse_colr</summary>

```c++

//Store.h
struct Color
{
	Color* next = nullptr;
	uint32_t colorKind;
	uint32_t colorIndex;
	int rgb[3];//0-255
}
//Store.cpp
Color * Store::newColor(Group * parent)
{
	assert(parent != nullptr);
	assert(parent->kind == Group::Kind::Model);
	auto * color = arena.alloc<Color>();
	color->next = nullptr;
	insert(parent->colors, color);
	return color;
}
//ParseRVM.cpp
  const char* read_color_be(int& rv, const char* p, const char* e)
  {
	  auto * q = reinterpret_cast<const uint8_t*>(p);
	  rv = q[0];
	  return p + 1;
  }
  const char* parse_colr(Context* ctx, const char* p, const char* e) {
	  assert(!ctx->group_stack.empty());
	  if (ctx->group_stack.back()->kind != Group::Kind::Model) {
		  ctx->store->setErrorString("Model chunk unfinished.");
		  return nullptr;
	  }
	  auto * g = ctx->store->newColor(ctx->group_stack.back());
	   p = read_uint32_be(g->colorKind, p, e);
	   p = read_uint32_be(g->colorIndex, p, e);
	  for (unsigned i = 0; i <3 ; i++) {
		  p= read_color_be(g->rgb[i], p, e);
	  }
	  return p+1;
  }
```
</details>
Greate thanks to this open source.

**Comment by cdyk** [comment]
Hi, thanks for your suggestions!

I have added your suggestions in the branch

https://github.com/cdyk/rvmparser/tree/parse_colr

Could you please verify that this code works as intended?

**Comment by dnsn021** [comment]
Hi, in my .rvm file, the color chunks not exist alpha params, so it works as intended after changing the range of the loop.
<details>
<summary>parse_colr method</summary>

```c++
//parse_colr method
    for (unsigned i = 0; i < 3; i++) {
      p = read_uint8(g->rgba[i], p, e);
    }
```
</details>

**Comment by cdyk** [comment]
Thanks! I'll add the fix and merge the branch.
