### ISSUE TITLE
Is there any chance to convert rvm file from binary to text

### ISSUE THREAD

**Issue by MBelal** [cdyk/rvmparser#9]
Is there any chance to convert rvm file from binary to text

**Comment by cdyk** [comment]
I have never seen a text-based rvm file, so I have no idea how to format the output.

That said, dumping the contents of an rvm-file should be pretty straight-forward - just implement a visitor ala `DumpNames.cpp` and write out all the properties.

**Comment by MBelal** [comment]
I have sample of rvm text files but i dont have a document for this format.

**Comment by MBelal** [comment]
So, if you have any document explaining this format , it will be very heplfull.

**Comment by cdyk** [comment]
No, unfortunately, I have no documentation on neither text nor binary rvm files. This parser was written by inspecting the source of pmuc and guessing the rest from binary dumps of rvm files.

**Comment by MBelal** [comment]
so, i will take my chances. make some inspections and I hope to come back with good results.

**Comment by cdyk** [comment]
I have looked on some text-based .rev-files, and started on export for that, see PR https://github.com/cdyk/rvmparser/pull/22.

**Comment by cdyk** [comment]
Partial support added
